{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      {{- if eq $name "demo-gateway-service" }}
      initContainers:
        - name: wait-for-eureka
          image: curlimages/curl:8.10.1
          command: ["/bin/sh","-c"]
          args:
            - >
              echo "Waiting for Eureka at {{ $.Values.global.eurekaUrl }}...";
              until curl -sf {{ $.Values.global.eurekaUrl }}actuator/health;
              do echo "Eureka not ready, retrying in 3s..."; sleep 3; done;
      {{- end }}
      containers:
        - name: {{ $name }}
          image: {{ $svc.image }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $svc.port }}
          env:
            {{- if $svc.env }}
            {{- toYaml $svc.env | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ $svc.healthPath }}
              port: {{ $svc.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
---
{{- end }}