apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-a
spec:
  replicas: {{ (index .Values.services "demo-service-a").replicaCount }}
  selector:
    matchLabels:
      app: demo-service-a
  template:
    metadata:
      labels:
        app: demo-service-a
    spec:
      containers:
      - name: demo-service-a
        image: {{ (index .Values.services "demo-service-a").image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}

        ports:
        - containerPort: {{ (index .Values.services "demo-service-a").port }}

        env:
        {{- range (index .Values.services "demo-service-a").env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}

        readinessProbe:
          httpGet:
            path: {{ (index .Values.services "demo-service-a").healthPath }}
            port: {{ (index .Values.services "demo-service-a").port }}

        livenessProbe:
          httpGet:
            path: {{ (index .Values.services "demo-service-a").healthPath }}
            port: {{ (index .Values.services "demo-service-a").port }}