apiVersion: v1
kind: Service
metadata:
  name: demo-gateway-service
spec:
  type: NodePort
  selector:
    app: demo-gateway-service
  ports:
  - port: {{ (index .Values.services "demo-gateway-service").servicePort }}
    targetPort: {{ (index .Values.services "demo-gateway-service").port }}
    nodePort: {{ (index .Values.services "demo-gateway-service").nodePort }}