{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  type: {{ if $svc.nodePort }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      port: {{ $svc.servicePort | default $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
      {{- if $svc.nodePort }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
---
{{- end }}