{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.servicePort }}
      targetPort: {{ $svc.port }}
      protocol: TCP
      name: http
  type: ClusterIP
---
{{- end }}